# NeuroTrailblazers - Jekyll Configuration
title: "NeuroTrailblazers"
description: "Illuminating Pathways for Trailblazing Neuroscience Researchers - A curriculum and mentorship platform for nanoscale connectomics discovery"
baseurl: "/neurotrailblazers"
url: "https://wrgr.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  modules:
    output: true
    permalink: /:collection/:name/
  archetypes:
    output: true
    permalink: /:collection/:name/
  datasets:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "modules"
    values:
      layout: "module"
  - scope:
      path: ""
      type: "archetypes"
    values:
      layout: "archetype"
  - scope:
      path: ""
      type: "datasets"
    values:
      layout: "dataset"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Site configuration
author: "NeuroTrailblazers Team"
email: "info@neurotrailblazers.org"
twitter_username: neurotrailblazers
github_username: wrgr

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Start Here"
    url: "/start-here"
  - title: "Models"
    url: "/models"
  - title: "Workflow"
    url: "/workflow"
  - title: "Modules"
    url: "/modules/"
    dropdown:
      - title: "Module 0: Inspiration"
        url: "/modules/module01/"
      - title: "Module 1: Introduction"
        url: "/modules/module02/"
      - title: "All Modules"
        url: "/modules/"
  - title: "Datasets"
    url: "/datasets/"
  - title: "Archetypes"
    url: "/archetypes/"

# Grant and program information
grant_info:
  program: "NIH CONNECTS"
  grant: "HI-MC"
  funding_agency: "National Institutes of Health"
  focus: "Nanoscale Connectomics"
  mission: "Closing knowledge and opportunity gaps for students who dream of shaping the future of neuroscience"

# Color palette
colors:
  neural_blue: "#2563eb"
  cerebral_purple: "#7c3aed"
  axon_cyan: "#06b6d4"
  brain_gray: "#f3f4f6"
  synapse_black: "#111827"

# Exclude from processing
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - scripts
