# NeuroTrailblazers - Jekyll Configuration
title: "NeuroTrailblazers"
description: "Illuminating Pathways for Trailblazing Neuroscience Researchers - A curriculum and mentorship platform for nanoscale connectomics discovery"
baseurl: ""
url: "https://neurotrailblazers.org"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  modules:
    output: true
    permalink: /:collection/:name/
  avatars:
    output: true
    permalink: /:collection/:name/
  datasets:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "modules"
    values:
      layout: "module"
  - scope:
      path: "modules"
      type: ""
    values:
      layout: "module"
      permalink: "/modules/:basename/"
  - scope:
      path: ""
      type: "avatars"
    values:
      layout: "avatar"
  - scope:
      path: ""
      type: "datasets"
    values:
      layout: "dataset"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Site configuration
author: "NeuroTrailblazers Team"
email: "info@neurotrailblazers.org"
twitter_username: neurotrailblazers
github_username: wrgr

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Start Here"
    url: "/start-here"
  - title: "Models"
    url: "/models"
  - title: "Workflow"
    url: "/datasets/workflow"
  - title: "Modules"
    url: "/modules/"
    dropdown: []
  - title: "Datasets"
    url: "/datasets/"
  - title: "Avatars"
    url: "/avatars/"
  - title: "Ask an Expert"
    url: "/ask-an-expert/"

# Grant and program information
grant_info:
  program: "NIH CONNECTS"
  grant: "HI-MC"
  funding_agency: "National Institutes of Health"
  focus: "Nanoscale Connectomics"
  mission: "Closing knowledge and opportunity gaps for students who dream of shaping the future of neuroscience"

# Program tagline used across pages
tagline_lines:
  - "We power breakthroughs by developing and deploying top research talent."
  - "Our research incubators equip students and mentors with the tools, guidance, and experience to accelerate innovation across cutting-edge fields such as neuroscience, AI, and decision science."
  - "Neurotrailblazers applies this framework to the audacious goal of mapping the networks of the brain at the level of individual synaptic connections, and makes tools, training and content available to the CONNECTS community and beyond."

# Color palette
colors:
  neural_blue: "#2563eb"
  cerebral_purple: "#7c3aed"
  axon_cyan: "#06b6d4"
  brain_gray: "#f3f4f6"
  synapse_black: "#111827"

# Exclude from processing
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - scripts
