#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate the synthetic teaching kits under assets/kits/.
#
# Why this exists. The session kits for Modules 03-07 and 09-11 (and several later
# modules) told learners to open "the provided" sample CSV, patch set, notebook or
# metric script, and the site published none of them (NEXT_CONTENT_PASS.md item 5;
# audit in docs/reviews/2026-09-kit-materials-audit.md). Where an honest stand-in
# could be built without pretending to be real data, it is built here. Where it could
# not (real EM image patches), the module was rewritten to use public viewers instead.
#
# Every file this script writes is SYNTHETIC. Nothing is sampled from MICrONS, H01,
# FlyWire or any other dataset; distributions are chosen by hand to make one teaching
# point each, and every README says so in its first lines. Output is deterministic:
# each kit draws from its own fixed seed, and floats are written with fixed precision,
# so re-running the script on any Ruby >= 3.1 reproduces the committed bytes.
#
# The hand-written analysis scripts in the kits (qc_metrics.py, morphometry.py,
# profile_join.py) are not generated. This script only lists them in the manifest.
#
# Run from anywhere:  ruby scripts/generate_kit_materials.rb
# Then check:         ruby scripts/validate_kit_materials.rb

require 'fileutils'
require 'digest'
require 'json'

ROOT = File.expand_path('..', __dir__)
KITS = File.join(ROOT, 'assets', 'kits')
GENERATOR = 'scripts/generate_kit_materials.rb'

SYNTHETIC_BANNER = <<~MD.strip
  > **Synthetic teaching data.** Every number in this kit was generated by
  > `#{GENERATOR}` from a fixed random seed. None of it is sampled from MICrONS, H01,
  > FlyWire or any other real dataset, and no result computed from it is a finding
  > about a brain. The distributions were chosen by hand so that one teaching point
  > is visible; real data are messier in ways this kit does not model.
MD

# ------------------------------------------------------------------ helpers

def kit_dir(num)
  dir = File.join(KITS, format('module%02d', num))
  FileUtils.mkdir_p(dir)
  dir
end

def write(path, text)
  FileUtils.mkdir_p(File.dirname(path))
  File.write(path, text.end_with?("\n") ? text : "#{text}\n")
end

def write_csv(path, header, rows)
  lines = [header.join(',')]
  rows.each do |row|
    lines << row.map { |v| csv_cell(v) }.join(',')
  end
  write(path, lines.join("\n"))
end

def csv_cell(value)
  s = case value
      when Float then value.to_s
      when nil then ''
      else value.to_s
      end
  s.match?(/[",\n]/) ? "\"#{s.gsub('"', '""')}\"" : s
end

def poisson(rng, lambda)
  return 0 if lambda <= 0

  l = Math.exp(-lambda)
  k = 0
  p = 1.0
  loop do
    p *= rng.rand
    break if p <= l

    k += 1
  end
  k
end

def gaussian(rng, mean = 0.0, sd = 1.0)
  u1 = rng.rand
  u1 = 1e-12 if u1 < 1e-12
  u2 = rng.rand
  mean + sd * Math.sqrt(-2.0 * Math.log(u1)) * Math.cos(2 * Math::PI * u2)
end

def weighted_pick(rng, weights)
  total = weights.values.sum
  r = rng.rand * total
  weights.each do |key, w|
    return key if r < w

    r -= w
  end
  weights.keys.last
end

def delim(n) = n.to_s.reverse.scan(/\d{1,3}/).join(',').reverse

def dist(a, b)
  Math.sqrt(a.zip(b).sum { |p, q| (p - q)**2 })
end

# ------------------------------------------------------------------ vectors

def vadd(a, b) = a.zip(b).map { |p, q| p + q }
def vscale(a, s) = a.map { |p| p * s }

def vnorm(a)
  n = Math.sqrt(a.sum { |p| p * p })
  n.zero? ? [0.0, 1.0, 0.0] : a.map { |p| p / n }
end

def jitter(rng, dir, amount)
  vnorm(vadd(dir, [gaussian(rng, 0, amount), gaussian(rng, 0, amount), gaussian(rng, 0, amount)]))
end

# ------------------------------------------------------------------ SWC trees
#
# A deliberately simple grower: a dendrite is a run of 2 µm steps with a small
# random wobble, bifurcating at its end until a depth limit. Spines are Poisson
# draws per step at a density that can depend on path distance from the soma.
# The grower stops a branch where it crosses the volume boundary and records the
# node, which is how truncation is represented.

class SwcTree
  attr_reader :nodes, :spines, :face_nodes

  def initialize(bounds)
    @bounds = bounds # [[xmin,xmax],[ymin,ymax],[zmin,zmax]] or nil
    @nodes = []
    @spines = Hash.new(0)
    @face_nodes = []
  end

  def add(type, pos, radius, parent)
    id = @nodes.size + 1
    @nodes << [id, type, pos, radius, parent]
    id
  end

  def outside?(pos)
    return false unless @bounds

    pos.each_with_index.any? { |c, i| c < @bounds[i][0] || c > @bounds[i][1] }
  end

  # Moves a point that left the volume back onto the face it crossed.
  def clamp(pos)
    pos.each_with_index.map { |c, i| c.clamp(@bounds[i][0], @bounds[i][1]) }
  end

  def pos(id) = @nodes[id - 1][2]

  # grow a branch; opts: length, radius, depth, max_depth, wobble, spine (lambda path_um -> density),
  # split_angle, shrink
  def grow(rng, parent, start, dir, type, opts, path0 = 0.0)
    step = 2.0
    steps = [(opts[:length] / step).round, 1].max
    cur = parent
    p = start
    r = opts[:radius]
    path = path0
    steps.times do
      dir = jitter(rng, dir, opts[:wobble])
      np = vadd(p, vscale(dir, step))
      path += step
      if outside?(np)
        np = clamp(np)
        id = add(type, np, r, cur)
        @face_nodes << id
        @spines[id] += poisson(rng, opts[:spine].call(path, type) * step)
        return
      end
      id = add(type, np, r, cur)
      @spines[id] += poisson(rng, opts[:spine].call(path, type) * step)
      cur = id
      p = np
      r = [r * opts.fetch(:taper, 0.985), 0.25].max
    end
    return if opts[:depth] >= opts[:max_depth]

    2.times do
      child_dir = jitter(rng, dir, opts[:split_angle])
      child = opts.merge(length: opts[:length] * (0.6 + 0.3 * rng.rand),
                         radius: r * 0.8, depth: opts[:depth] + 1)
      grow(rng, cur, p, child_dir, type, child, path)
    end
  end

  def swc_text(header_lines)
    lines = header_lines.map { |l| "# #{l}" }
    lines << '# columns: id type x y z radius parent  (type 1 soma, 3 basal dendrite, 4 apical dendrite)'
    @nodes.each do |id, type, pos, r, parent|
      lines << format('%d %d %.2f %.2f %.2f %.2f %d', id, type, pos[0], pos[1], pos[2], r, parent)
    end
    lines.join("\n")
  end
end

PYR_SPINES = lambda do |path, type|
  if type == 4 && path < 40 then 0.15 # proximal apical trunk carries few spines
  elsif path < 12 then 0.3            # first microns of any dendrite are nearly smooth
  else 1.3
  end
end
SMOOTH_SPINES = ->(_path, _type) { 0.03 }

def pyramidal(rng, tree, soma, apical_dir: [0.0, 1.0, 0.0], basal_dirs: nil, apical_len: 110,
              basal_len: 42, spine: PYR_SPINES)
  sid = tree.add(1, soma, 7.0, -1)
  base = { radius: 1.1, depth: 0, max_depth: 2, wobble: 0.12, split_angle: 0.55, spine: spine }
  tree.grow(rng, sid, soma, vnorm(apical_dir), 4,
            base.merge(length: apical_len, radius: 1.8, max_depth: 2, taper: 0.992))
  basal_dirs ||= Array.new(5) do |i|
    a = 2 * Math::PI * i / 5 + rng.rand * 0.4
    [Math.cos(a), -0.35 - 0.2 * rng.rand, Math.sin(a)]
  end
  basal_dirs.each { |d| tree.grow(rng, sid, soma, vnorm(d), 3, base.merge(length: basal_len)) }
  sid
end

def interneuron(rng, tree, soma, n_dend: 6, length: 55, spine: SMOOTH_SPINES, max_depth: 3)
  sid = tree.add(1, soma, 6.0, -1)
  n_dend.times do |i|
    a = 2 * Math::PI * i / n_dend + rng.rand * 0.5
    d = [Math.cos(a), gaussian(rng, 0, 0.6), Math.sin(a)]
    tree.grow(rng, sid, soma, vnorm(d), 3,
              { length: length, radius: 0.8, depth: 0, max_depth: max_depth, wobble: 0.22,
                split_angle: 0.7, spine: spine })
  end
  sid
end

# ------------------------------------------------------------------ Module 03

def module03
  rng = Random.new(3003)
  dir = kit_dir(3)
  types = {
    'L23_pyr' => ['L2/3', 90], 'L4_exc' => ['L4', 70], 'L5_pyr' => ['L5', 60],
    'basket' => [nil, 40], 'martinotti' => [nil, 25], 'vip' => [nil, 15]
  }
  neurons = []
  nid = 100_001
  types.each do |type, (layer, n)|
    n.times do
      region = layer || %w[L2/3 L4 L5].sample(random: rng)
      depth = { 'L2/3' => [100, 300], 'L4' => [300, 450], 'L5' => [450, 700] }[region]
      neurons << { id: nid, type: type, region: region,
                   pos: [rng.rand * 300, depth[0] + rng.rand * (depth[1] - depth[0]), rng.rand * 300] }
      nid += 1
    end
  end
  exc = %w[L23_pyr L4_exc L5_pyr]
  out_weight = lambda do |pre, post|
    if exc.include?(pre.fetch(:type))
      exc.include?(post[:type]) ? 1.0 : 1.6
    else
      post[:type] == 'vip' ? 0.3 : 1.2
    end
  end
  rows = []
  sid = 1
  3000.times do
    pre = neurons.sample(random: rng)
    post = nil
    loop do
      cand = neurons.sample(random: rng)
      next if cand[:id] == pre[:id]

      d = dist(pre[:pos], cand[:pos])
      p = out_weight.call(pre, cand) * Math.exp(-d / 180.0) / 1.6
      if rng.rand < p
        post = cand
        break
      end
    end
    loc = vadd(post[:pos], [gaussian(rng, 0, 25), gaussian(rng, 0, 25), gaussian(rng, 0, 25)])
    size = (exc.include?(pre[:type]) ? 180 : 260) * Math.exp(gaussian(rng, 0, 0.6))
    rows << [sid, pre[:id], post[:id], pre[:type], post[:type], post[:region],
             loc[0].round(1), loc[1].round(1), loc[2].round(1), size.round]
    sid += 1
  end
  # Two percent of rows lack a postsynaptic cell type, as real annotation tables do;
  # schema validation in step 4 should find them.
  rows.each { |r| r[4] = '' if rng.rand < 0.02 }
  write_csv(File.join(dir, 'synapses_sample.csv'),
            %w[synapse_id pre_root_id post_root_id pre_cell_type post_cell_type region x_um y_um z_um size_vx],
            rows)
  meta = {
    'dataset' => 'synthetic-teaching-only',
    'version' => 'synthetic-synapses-v1',
    'generator' => GENERATOR,
    'seed' => 3003,
    'rows' => rows.size,
    'neurons' => neurons.size,
    'columns' => {
      'synapse_id' => 'row identifier',
      'pre_root_id' => 'synthetic presynaptic neuron ID (six digits; real CAVE root IDs are 18 digits)',
      'post_root_id' => 'synthetic postsynaptic neuron ID',
      'pre_cell_type' => 'L23_pyr, L4_exc, L5_pyr, basket, martinotti or vip',
      'post_cell_type' => 'same vocabulary; blank for about 2.5% of rows (missing annotation)',
      'region' => 'layer of the postsynaptic soma: L2/3, L4 or L5',
      'x_um y_um z_um' => 'synapse position in micrometers; y increases with depth from the pia',
      'size_vx' => 'cleft size in voxels (arbitrary synthetic units)'
    },
    'limitation' => 'Invented cell types, positions and connection rules; not a CAVE query and not a biological measurement.'
  }
  write(File.join(dir, 'synapses_sample.meta.json'), JSON.pretty_generate(meta))
  write(File.join(dir, 'README.md'), <<~MD)
    # Module 03 kit: offline synapse table

    #{SYNTHETIC_BANNER}

    Use this when CAVE access is unavailable (Module 03 studio activity, step 3). It
    has the shape of a small synapse query result, so every step of the activity
    works on it: schema validation, filtering by region, grouping by cell-type pair,
    a figure, and a CSV plus metadata export.

    | File | What it is |
    |---|---|
    | `synapses_sample.csv` | #{delim(rows.size)} synapses among #{neurons.size} invented neurons |
    | `synapses_sample.meta.json` | Column definitions, version string and seed |

    Record `synthetic-synapses-v1` as the dataset version in your notebook header, in
    the place a materialization version would go. The file deliberately contains a
    few rows with a blank `post_cell_type`; your schema check should report how many.

    Load it with pandas:

    ```python
    import pandas as pd
    syn = pd.read_csv("synapses_sample.csv")
    print(syn.dtypes, len(syn))
    print(syn["post_cell_type"].eq("").sum() + syn["post_cell_type"].isna().sum(), "rows lack a post type")
    ```

    **What this file cannot teach.** Authentication, materialization versions that
    change under you, and query limits. Do those against a real CAVE endpoint when you
    have access; the [Dataset Access](/datasets/access/) page lists the entry points.
  MD
end

# ------------------------------------------------------------------ Modules 06 and 07
#
# A flag report a learner triages, a ground-truth file an instructor holds back, and
# a shared metric script (qc_metrics.py) that plays the part of the comparison you
# would run against a proofread reference region.

TRIAGE_GT_HEADER = %w[id true_type false_edges missed_edges false_reciprocal hidden_reciprocal
                      on_analysis_cell size_outlier misassigned_synapses].freeze

def triage_readme(num, title:, scenario:, report:, fixes:, warmup:, extra:)
  <<~MD
    # Module #{format('%02d', num)} kit: #{title}

    #{SYNTHETIC_BANNER}

    #{scenario}

    | File | Who opens it | What it is |
    |---|---|---|
    | `#{report}` | Learners | The flag list you triage. It shows only what a proofreader sees before editing. |
    | `ground_truth.csv` | Instructor | What each fix would actually change. Hold it back until rankings are committed. |
    | `kit.json` | Script | Totals for the analysis set, the fix budget, and file names. |
    | `qc_metrics.py` | Everyone | Computes before/after quality indicators for a list of fixed IDs. Python 3, no packages. |

    **Fixing on paper.** No public volume lets a class edit a segmentation, so a "fix"
    here means: you commit to correcting a flagged item, write its log line, and then
    let the script apply what that correction would have changed. The script stands
    in for re-measuring against a proofread reference region. It knows the answer;
    you do not, which is the situation a real triage is in.

    ```bash
    python3 qc_metrics.py                      # baseline, nothing fixed
    python3 qc_metrics.py --fixed #{fixes}     # after your fixes (IDs comma-separated)
    ```

    #{warmup}

    #{extra}

    **What this kit cannot teach.** Reading the evidence in the image. Every flag here
    arrives with a written note; in a real volume the note is what you have to produce.
    Practice that part on a public volume (the [proofreading side quest](/side-quests/proofreading/)
    uses real data), and use this kit for the part that is about allocation.
  MD
end

def triage_rows(rng, specs)
  specs.flat_map do |spec|
    Array.new(spec[:n]) { spec }
  end.shuffle(random: rng)
end

def module07
  rng = Random.new(7007)
  dir = kit_dir(7)
  z = -> { 200 + rng.rand(800) }
  specs = [
    # merges, 18
    { n: 5, flag: 'merge', cls: 'L2/3 pyramidal', roi: 'yes', syn: 260..520, score: 0.62..0.95,
      notes: ['two somata in one object; thin bridge near section %d', 'apical dendrites of two cells joined across a fold at section %d',
              'soma count 2; caliber drops 0.9 to 0.2 um at section %d'],
      gt: { true_type: 'merge', fe: 10..18, me: 0..0, fr: 1..3, hr: 0..0, cell: 1 } },
    { n: 4, flag: 'merge', cls: 'L2/3 pyramidal', roi: 'yes', syn: 180..400, score: 0.55..0.85,
      notes: ['smooth branch joins spiny pyramidal arbor at section %d', 'aspiny process attached to basal dendrite at section %d'],
      gt: { true_type: 'merge', fe: 3..7, me: 0..0, fr: 0..1, hr: 0..0, cell: 1 } },
    { n: 4, flag: 'merge', cls: 'glia', roi: 'yes', syn: 0..12, score: 0.80..0.99,
      notes: ['very large irregular mesh; astrocytic sheet fused to several axons near section %d',
              'glial object wraps a blood vessel and absorbs two axon fragments at section %d'],
      gt: { true_type: 'merge', fe: 0..2, me: 0..0, fr: 0..0, hr: 0..0, cell: 0 } },
    { n: 3, flag: 'merge', cls: 'interneuron', roi: 'yes', syn: 300..700, score: 0.60..0.90,
      notes: ['interneuron axon fused with a neighboring interneuron dendrite at section %d'],
      gt: { true_type: 'merge', fe: 0..1, me: 0..0, fr: 0..0, hr: 0..0, cell: 0 } },
    { n: 2, flag: 'merge', cls: 'L2/3 pyramidal', roi: 'no', syn: 200..450, score: 0.70..0.95,
      notes: ['two somata in one object at the volume corner, section %d'],
      gt: { true_type: 'merge', fe: 0..0, me: 0..0, fr: 0..0, hr: 0..0, cell: 0 } },
    # splits, 20
    { n: 6, flag: 'split', cls: 'L2/3 pyramidal', roi: 'yes', syn: 40..160, score: 0.50..0.85,
      notes: ['axon of an analysis-set cell ends abruptly at missing section section %d',
              'main axon dead-ends in a low-contrast stretch at section %d; continuation candidate 3 sections on'],
      gt: { true_type: 'split', fe: 0..0, me: 7..14, fr: 0..0, hr: 1..2, cell: 1 } },
    { n: 3, flag: 'split', cls: 'L2/3 pyramidal', roi: 'yes', syn: 10..40, score: 0.45..0.75,
      notes: ['distal dendrite branch detached at section %d'],
      gt: { true_type: 'split', fe: 0..0, me: 1..3, fr: 0..0, hr: 0..0, cell: 1 } },
    { n: 5, flag: 'split', cls: 'glia', roi: 'yes', syn: 0..0, score: 0.85..0.99,
      notes: ['astrocytic process fragmented into 12+ pieces around section %d', 'glial sheet broken into many small objects near section %d'],
      gt: { true_type: 'split', fe: 0..0, me: 0..0, fr: 0..0, hr: 0..0, cell: 0 } },
    { n: 3, flag: 'split', cls: 'unknown fragment', roi: 'yes', syn: 1..8, score: 0.60..0.90,
      notes: ['orphan axon fragment, 20-40 um, no soma in volume, z=%d'],
      gt: { true_type: 'split', fe: 0..0, me: 0..1, fr: 0..0, hr: 0..0, cell: 0 } },
    { n: 3, flag: 'split', cls: 'L2/3 pyramidal', roi: 'no', syn: 30..120, score: 0.55..0.85,
      notes: ['dendrite dead-ends at the volume edge, z=%d'],
      gt: { true_type: 'split', fe: 0..0, me: 0..0, fr: 0..0, hr: 0..0, cell: 0 } },
    # uncertain, 7
    { n: 3, flag: 'uncertain', cls: 'L2/3 pyramidal', roi: 'yes', syn: 150..380, score: 0.35..0.55,
      notes: ['caliber change without a visible membrane at z=%d; could be a merge'],
      gt: { true_type: 'merge', fe: 6..12, me: 0..0, fr: 1..2, hr: 0..0, cell: 1 } },
    { n: 2, flag: 'uncertain', cls: 'L2/3 pyramidal', roi: 'yes', syn: 60..140, score: 0.30..0.50,
      notes: ['possible missed continuation across a fold at z=%d'],
      gt: { true_type: 'split', fe: 0..0, me: 4..8, fr: 0..0, hr: 0..1, cell: 1 } },
    { n: 2, flag: 'uncertain', cls: 'L2/3 pyramidal', roi: 'yes', syn: 120..300, score: 0.30..0.45,
      notes: ['odd branching angle at z=%d; membrane looks continuous'],
      gt: { true_type: 'not_error', fe: 0..0, me: 0..0, fr: 0..0, hr: 0..0, cell: 0 } }
  ]
  rows = triage_rows(rng, specs)
  report = []
  truth = []
  rows.each_with_index do |spec, i|
    id = format('E%02d', i + 1)
    seg = 7_000 + rng.rand(3_000)
    other = spec[:flag] == 'split' ? '' : 7_000 + rng.rand(3_000)
    pos = [(rng.rand * 100).round(1), (rng.rand * 100).round(1), (rng.rand * 100).round(1)]
    note = format(spec[:notes].sample(random: rng), z.call)
    report << [id, spec[:flag], seg, other, spec[:cls], spec[:roi], rng.rand(spec[:syn]),
               rng.rand(spec[:score]).round(2), pos[0], pos[1], pos[2], note]
    g = spec[:gt]
    truth << [id, g[:true_type], rng.rand(g[:fe]), rng.rand(g[:me]), rng.rand(g[:fr]), rng.rand(g[:hr]),
              g[:cell], 0, 0]
  end
  write_csv(File.join(dir, 'error_report.csv'),
            %w[error_id detector_flag segment_id other_segment_id putative_class in_analysis_roi
               synapses_on_segment detector_score x_um y_um z_um detector_note], report)
  write_csv(File.join(dir, 'ground_truth.csv'), TRIAGE_GT_HEADER, truth)
  kit = {
    'dataset' => 'synthetic-teaching-only',
    'version' => 'synthetic-error-report-v1',
    'seed' => 7007,
    'report_file' => 'error_report.csv',
    'id_column' => 'error_id',
    'flag_column' => 'detector_flag',
    'ground_truth_file' => 'ground_truth.csv',
    'fix_budget' => 15,
    'analysis' => {
      'description' => 'Directed connections among the 60 L2/3 pyramidal cells in the ROI',
      'analysis_cells' => 60,
      'true_edges' => 400,
      'true_reciprocal_pairs' => 40,
      'analysis_path_um' => 36_000,
      'unflagged_error_sites' => 1_250
    },
    'limitation' => 'Invented error report and effects. The run-length proxy is not the ERL of Funke et al.; it divides analysis-cell path by error sites and assumes errors are spread evenly.'
  }
  write(File.join(dir, 'kit.json'), JSON.pretty_generate(kit))
  write(File.join(dir, 'README.md'), triage_readme(
    7, title: 'automated error report and metric script',
    scenario: 'This kit is the automated error report and the metric computation script for the ' \
              'Module 07 release decision simulation: 45 flags (18 merge, 20 split, 7 uncertain) ' \
              'for a 100 x 100 x 100 µm subvolume whose planned analysis is reciprocal connectivity ' \
              'among 60 L2/3 pyramidal cells.',
    report: 'error_report.csv', fixes: 'E03,E11,E17',
    warmup: '**Run-of-show warm-up.** The 10:00-24:00 queue classification exercise uses rows ' \
            '`E01` to `E12` only; pairs rank their top 5 and apply them with the script in the ' \
            '24:00-38:00 sprint. The studio activity uses all 45 rows and a budget of 15 fixes.',
    extra: <<~TXT.strip
      **What the script reports.** Edge precision, recall and F1 for connections among
      the analysis cells (the synapse-centric metric), how many reciprocal pairs the
      analysis would count and how many of those are spurious, and a run-length proxy.
      The proxy moves very little when you fix 15 flags, because most error sites in a
      volume are never flagged at all (`unflagged_error_sites` in `kit.json`). That is
      deliberate: when the question-specific metric and the aggregate metric disagree,
      the memo has to say which one the reciprocal-connectivity question depends on.
      The run-of-show thresholds (run length > 30 µm, F1 > 0.80) are the ones to test.
    TXT
  ))
end

def module06
  rng = Random.new(6006)
  dir = kit_dir(6)
  z = -> { 900 + rng.rand(400) }
  specs = [
    { n: 5, reason: 'implausible morphology', cls: 'L2/3 pyramidal', set: 'yes', syn: 150..260, partners: 35..60,
      vol: 2400..4200, mins: 25..45,
      notes: ['two somata about %d um apart joined by one thin process', 'caliber drops from 0.8 to 0.2 um across a fold; object is twice the usual volume (%d um3 excess)'],
      gt: { true_type: 'merge', fe: 8..16, me: 0..0, cell: 1, outlier: 1, mis: 0..0 } },
    { n: 3, reason: 'implausible morphology', cls: 'glia', set: 'no', syn: 0..6, partners: 0..3,
      vol: 5000..9000, mins: 30..60,
      notes: ['very large sheet-like object wrapping %d um of vessel', 'astrocytic mesh with %d attached fragments'],
      gt: { true_type: 'merge', fe: 0..0, me: 0..0, cell: 0, outlier: 0, mis: 0..0 } },
    { n: 5, reason: 'dead-end fragment', cls: 'L2/3 pyramidal', set: 'yes', syn: 20..70, partners: 8..20,
      vol: 300..900, mins: 20..40,
      notes: ['axon of an analysis-set cell ends at a missing section, continuation %d sections on', 'dendrite dead-ends in a low-contrast stretch %d um from the soma'],
      gt: { true_type: 'split', fe: 0..0, me: 4..9, cell: 1, outlier: 0, mis: 0..0 } },
    { n: 5, reason: 'dead-end fragment', cls: 'unknown fragment', set: 'no', syn: 2..12, partners: 1..6,
      vol: 20..120, mins: 30..40,
      notes: ['%d um axon fragment, parent cell outside the analysis set', 'orphan fragment ending at a missing section (%d um long)'],
      gt: { true_type: 'split', fe: 0..0, me: 0..0, cell: 0, outlier: 0, mis: 0..0 } },
    { n: 4, reason: 'synapse near boundary', cls: 'L2/3 pyramidal', set: 'yes', syn: 80..200, partners: 20..45,
      vol: 1200..2000, mins: 10..20,
      notes: ['membrane offset by about 2 px; %d synapses sit on the wrong side', 'cleft straddles two objects; %d synapses attributed to the neighbor'],
      gt: { true_type: 'boundary', fe: 1..3, me: 1..3, cell: 1, outlier: 0, mis: 3..9 } },
    { n: 3, reason: 'implausible morphology', cls: 'L2/3 pyramidal', set: 'yes', syn: 120..220, partners: 30..50,
      vol: 1300..2100, mins: 20..30,
      notes: ['unusual branch angle %d um from the soma; membrane looks continuous', 'thick process with a kink; %d sections checked, no boundary seen'],
      gt: { true_type: 'not_error', fe: 0..0, me: 0..0, cell: 0, outlier: 0, mis: 0..0 } }
  ]
  rows = triage_rows(rng, specs)
  report = []
  truth = []
  rows.each_with_index do |spec, i|
    id = format('C%02d', i + 1)
    note = format(spec[:notes].sample(random: rng), 3 + rng.rand(200))
    report << [id, 5_000 + rng.rand(4_000), spec[:reason], spec[:cls], spec[:set], rng.rand(spec[:syn]),
               rng.rand(spec[:partners]), rng.rand(spec[:vol]), rng.rand(spec[:mins]), "#{note}; z=#{z.call}"]
    g = spec[:gt]
    truth << [id, g[:true_type], rng.rand(g[:fe]), rng.rand(g[:me]), 0, 0, g[:cell], g[:outlier], rng.rand(g[:mis])]
  end
  write_csv(File.join(dir, 'flagged_candidates.csv'),
            %w[candidate_id object_id flag_reason putative_class in_analysis_set synapses partners
               volume_um3 est_fix_minutes evidence_note], report)
  write_csv(File.join(dir, 'ground_truth.csv'), TRIAGE_GT_HEADER, truth)
  kit = {
    'dataset' => 'synthetic-teaching-only',
    'version' => 'synthetic-flags-v1',
    'seed' => 6006,
    'report_file' => 'flagged_candidates.csv',
    'id_column' => 'candidate_id',
    'flag_column' => 'flag_reason',
    'ground_truth_file' => 'ground_truth.csv',
    'fix_budget' => 10,
    'analysis' => {
      'description' => 'Directed connections among the 40 L2/3 pyramidal cells in the analysis set',
      'analysis_cells' => 40,
      'true_edges' => 300,
      'true_reciprocal_pairs' => 0,
      'analysis_path_um' => 16_000,
      'unflagged_error_sites' => 520
    },
    'limitation' => 'Invented flags and effects; the size-outlier and misassigned-synapse counts stand in for the local indicators named in Module 06.'
  }
  write(File.join(dir, 'kit.json'), JSON.pretty_generate(kit))
  # The metric script is shared with Module 07, where it is maintained.
  shared = File.join(KITS, 'module07', 'qc_metrics.py')
  FileUtils.cp(shared, File.join(dir, 'qc_metrics.py')) if File.exist?(shared)
  write(File.join(dir, 'README.md'), triage_readme(
    6, title: 'flagged candidates for correction triage',
    scenario: 'This kit is the flag list for the Module 06 correction triage simulation: 25 ' \
              'candidates flagged by automated detection in a 50 x 50 x 50 µm subvolume of about ' \
              '200 fragments, ahead of a connectivity analysis of 40 L2/3 pyramidal cells. You ' \
              'have time to fix 10. The flag reason is what the detector saw; the error type ' \
              '(merge, split, boundary or uncertain) is yours to assign.',
    report: 'flagged_candidates.csv', fixes: 'C02,C09,C14',
    warmup: '**Run-of-show guided round.** The 22:00-36:00 pairs exercise uses three candidates ' \
            'chosen by the instructor from this file: one the class will agree is a merge, one a ' \
            'split, and one of the `implausible morphology` rows whose note says the membrane ' \
            'looks continuous (the ambiguous case).',
    extra: <<~TXT.strip
      **What the script reports.** Edge precision and recall for the analysis set, the
      number of analysis objects still outside the plausible size range for their type,
      synapses still attributed to the wrong neuron, and how many of your fixes were
      spent on items that were not errors. Those are the before/after indicators the
      rubric asks you to attach to each correction.
    TXT
  ))
end

# ------------------------------------------------------------------ Module 09 (and 16)

def cell_header(id, kind)
  ["cell #{id}: #{kind}", 'synthetic teaching morphology generated by ' + GENERATOR,
   'dendrites only; the axon is not included', 'units: micrometers']
end

def module09
  rng = Random.new(9009)
  dir = kit_dir(9)
  bounds = [[0.0, 300.0], [0.0, 300.0], [0.0, 220.0]]
  cells = {}
  plan = {
    '01' => [:pyr, [90, 120, 110]], '02' => [:pyr, [150, 110, 105]], '03' => [:int, [210, 160, 110]],
    '04' => [:pyr, [120, 90, 115]], '05' => [:int_merge, [170, 130, 108]], '06' => [:pyr, [100, 100, 100]],
    '07' => [:pyr_trunc, [270, 150, 110]], '08' => [:pyr, [190, 100, 112]], '09' => [:int, [130, 180, 110]],
    '10' => [:int, [200, 200, 105]]
  }
  plan.each do |cid, (kind, soma)|
    tree = SwcTree.new(bounds)
    case kind
    when :pyr
      pyramidal(rng, tree, soma, apical_len: 110, basal_len: 45)
    when :int
      interneuron(rng, tree, soma, length: 26)
    when :int_merge
      sid = interneuron(rng, tree, soma, length: 26)
      # A spiny dendrite fragment from a neighboring pyramidal cell, merged onto the
      # end of one smooth dendrite: the kind of merge that raises spine density.
      tips = tree.nodes.select { |n| n[4] != -1 && tree.nodes.none? { |m| m[4] == n[0] } }
      tip = tips.max_by { |n| dist(n[2], soma) }
      tree.grow(rng, tip[0], tip[2], vnorm(vadd(tip[2], vscale(soma, -1))), 3,
                { length: 80, radius: 1.0, depth: 0, max_depth: 2, wobble: 0.1, split_angle: 0.5,
                  spine: ->(_p, _t) { 1.5 } })
      sid
    when :pyr_trunc
      # Soma 30 µm from the +x face, as in the Module 09 worked example. The thick,
      # spine-poor apical trunk runs obliquely and leaves the volume; four basal
      # dendrites head for the face and are cut within a few tens of microns, before
      # they reach their spiny stretch; one basal dendrite stays inside.
      trunc_spines = lambda do |path, type|
        if type == 4 then 0.12
        elsif path < 25 then 0.3
        else 1.3
        end
      end
      sid = tree.add(1, soma, 7.0, -1)
      tree.grow(rng, sid, soma, vnorm([0.45, 1.0, 0.0]), 4,
                { length: 160, radius: 1.8, depth: 0, max_depth: 0, wobble: 0.05, split_angle: 0.5,
                  spine: trunc_spines, taper: 0.995 })
      [[1.0, -0.3, 0.2], [1.0, -0.2, -0.3], [1.0, 0.1, 0.4], [0.9, -0.5, -0.2]].each do |d|
        tree.grow(rng, sid, soma, vnorm(d), 3,
                  { length: 45, radius: 1.1, depth: 0, max_depth: 1, wobble: 0.08, split_angle: 0.5,
                    spine: trunc_spines })
      end
      tree.grow(rng, sid, soma, vnorm([-1.0, -0.4, 0.2]), 3,
                { length: 30, radius: 1.1, depth: 0, max_depth: 1, wobble: 0.1, split_angle: 0.55,
                  spine: trunc_spines })
      # Seven terminal twigs under 2 µm on interior nodes within 15 µm of the cut
      # face: skeletonization noise along the segmentation boundary.
      parents = tree.nodes.map { |n| n[4] }
      near = tree.nodes.select { |n| n[1] != 1 && n[2][0] > 285 && parents.include?(n[0]) }
      near.sample(7, random: rng).each do |anchor|
        stub = vadd(anchor[2], vscale(vnorm([gaussian(rng), gaussian(rng), gaussian(rng)]), 1.0 + rng.rand * 0.8))
        tree.add(anchor[1], tree.clamp(stub), 0.3, anchor[0])
      end
    end
    cells[cid] = [kind, tree]
  end
  kind_label = Hash.new('skeleton from automated segmentation')
  spine_rows = []
  cells.each do |cid, (kind, tree)|
    write(File.join(dir, 'skeletons', "cell#{cid}.swc"), tree.swc_text(cell_header(cid, kind_label[kind])))
    tree.spines.keys.sort.each do |node|
      tree.spines[node].times { spine_rows << ["cell#{cid}", node] }
    end
  end
  write_csv(File.join(dir, 'spines.csv'), %w[cell_id node_id], spine_rows)
  labels = {
    '01' => ['excitatory', 42, 0.95, 0.81, 'high'], '02' => ['excitatory', 37, 0.92, 0.78, 'high'],
    '03' => ['inhibitory', 55, 0.07, 0.12, 'high'], '04' => ['excitatory', 29, 0.90, 0.74, 'high'],
    '05' => ['inhibitory', 48, 0.10, 0.15, 'high'], '06' => ['excitatory', 33, 0.94, 0.80, 'high'],
    '07' => ['excitatory', 9, 0.89, 0.78, 'medium (few output synapses in volume)'],
    '08' => ['excitatory', 40, 0.93, 0.83, 'high'], '09' => ['inhibitory', 61, 0.05, 0.10, 'high'],
    '10' => ['inhibitory', 44, 0.09, 0.14, 'high']
  }
  write_csv(File.join(dir, 'synapse_labels.csv'),
            %w[cell_id synapse_call output_synapses_in_volume frac_asymmetric frac_onto_spines call_confidence],
            labels.map { |cid, (call, n, asym, spine, conf)| ["cell#{cid}", call, n, asym, spine, conf] })
  write(File.join(dir, 'volume.json'), JSON.pretty_generate(
    'dataset' => 'synthetic-teaching-only', 'version' => 'synthetic-skeletons-v1', 'seed' => 9009,
    'bounds_um' => { 'x' => bounds[0], 'y' => bounds[1], 'z' => bounds[2] },
    'axes' => 'y increases toward the pia',
    'limitation' => 'Procedural trees, not reconstructions of real neurons.'
  ))
  write(File.join(dir, 'README.md'), <<~MD)
    # Module 09 kit: ten skeletons and a synapse-based classification

    #{SYNTHETIC_BANNER}

    The Module 09 comparative morphometry activity: ten dendritic skeletons in a
    300 x 300 x 220 µm volume, a table of spine positions, and a synapse-based
    excitatory/inhibitory call for each cell to compare your morphological call
    against (studio step 4).

    | File | What it is |
    |---|---|
    | `skeletons/cell01.swc` ... `cell10.swc` | Dendrites in SWC (id, type, x, y, z, radius, parent). Axons are not included. |
    | `spines.csv` | One row per spine: the cell and the skeleton node it sits on |
    | `synapse_labels.csv` | The synapse-based call, from each cell's output synapses (not included as geometry) |
    | `volume.json` | Volume bounds, so you can tell a real tip from a cut at the face |
    | `morphometry.py` | Computes the five studio descriptors, per-dendrite detail and Sholl counts. Python 3, no packages. |

    ```bash
    python3 morphometry.py                       # descriptor table for all ten cells
    python3 morphometry.py --cell cell07 --detail  # per-dendrite cable, spines, face contact
    python3 morphometry.py --cell cell02 --sholl 10  # Sholl intersections every 10 µm
    ```

    If you have NeuroM installed you can load the SWC files with it instead; the
    script exists so that nobody is blocked by an install.

    **What is planted.** At least two cells will not classify cleanly from whole-cell
    descriptors, for two different reconstruction reasons. The studio asks you to find
    the reason, not just the mismatch. The instructor key is in the Module 09 row of
    `docs/reviews/2026-09-kit-materials-audit.md` in the repository, not on the site.

    **"Arbor volume."** The script reports the axis-aligned bounding box of the
    dendrites. That is a crude stand-in for a convex hull and overstates the volume of
    oblique arbors; say so if you use it.
  MD
  cells
end

def module16
  rng = Random.new(1616)
  dir = kit_dir(16)
  # Three example neurons for the Sholl figure: no volume boundary, so no truncation.
  specs = {
    'excitatory' => lambda { |t| pyramidal(rng, t, [0.0, 0.0, 0.0], apical_len: 120, basal_len: 45) },
    'basket' => lambda { |t| interneuron(rng, t, [0.0, 0.0, 0.0], n_dend: 7, length: 50, max_depth: 3) },
    'chandelier' => lambda { |t| interneuron(rng, t, [0.0, 0.0, 0.0], n_dend: 4, length: 70, max_depth: 2) }
  }
  neuron_rows = []
  specs.each do |name, build|
    tree = SwcTree.new(nil)
    build.call(tree)
    write(File.join(dir, 'neurons', "#{name}.swc"),
          tree.swc_text(["#{name} example neuron", 'synthetic teaching morphology generated by ' + GENERATOR,
                         'dendrites only', 'units: micrometers']))
    neuron_rows << [name, "neurons/#{name}.swc", { 'excitatory' => 0.08, 'basket' => 0.15, 'chandelier' => 0.22 }[name]]
  end
  write_csv(File.join(dir, 'neurons.csv'), %w[neuron file est_missing_cable_fraction], neuron_rows)

  # 50 x 50 cell-type matrix built from five families so that clustering has
  # something to find; about a third of pairs rest on fewer than 10 connections.
  families = %w[L23 L4 L5 L6 INH]
  types = families.flat_map { |f| (1..10).map { |i| format('%s_%02d', f, i) } }
  fam = ->(t) { t.split('_').first }
  syn = []
  conn = []
  types.each do |pre|
    srow = []
    crow = []
    types.each do |post|
      base = if fam.(pre) == fam.(post) then 40.0
             elsif fam.(pre) == 'INH' || fam.(post) == 'INH' then 22.0
             else 7.0
             end
      c = poisson(rng, base * Math.exp(gaussian(rng, 0, 0.7)))
      s = c.zero? ? 0 : c + poisson(rng, c * 1.6)
      crow << c
      srow << s
    end
    syn << [pre] + srow
    conn << [pre] + crow
  end
  write_csv(File.join(dir, 'celltype_synapses.csv'), ['pre_type'] + types, syn)
  write_csv(File.join(dir, 'celltype_connections.csv'), ['pre_type'] + types, conn)

  layer_rows = []
  { 'L2/3' => 820, 'L4' => 1040, 'L5' => 1310, 'L6' => 760 }.each do |layer, mean|
    40.times do |i|
      layer_rows << [format('%s-%02d', layer.delete('/'), i + 1), layer,
                     (mean * Math.exp(gaussian(rng, 0, 0.35))).round]
    end
  end
  write_csv(File.join(dir, 'input_synapses_by_layer.csv'), %w[neuron_id layer input_synapses], layer_rows)
  FileUtils.cp(File.join(KITS, 'module09', 'morphometry.py'), File.join(dir, 'morphometry.py')) if
    File.exist?(File.join(KITS, 'module09', 'morphometry.py'))
  write(File.join(dir, 'README.md'), <<~MD)
    # Module 16 kit: data for the figure package

    #{SYNTHETIC_BANNER}

    Data for the Module 16 figure build (20:00-35:00) and the three-figure studio
    package. Load it into whichever plotting tool you use; the activity is the figure,
    not the loading.

    | File | Figure | What it is |
    |---|---|---|
    | `celltype_synapses.csv` | 1 | 50 x 50 synapse counts, rows presynaptic type, columns postsynaptic type |
    | `celltype_connections.csv` | 1 | Number of connected neuron pairs behind each cell; hatch cells under 10 (studio) or 5 (warm-up) |
    | `neurons/excitatory.swc`, `basket.swc`, `chandelier.swc` | 2 | Three example dendritic arbors, soma at the origin |
    | `neurons.csv` | 2 | Estimated fraction of cable missing from each reconstruction, for the uncertainty band |
    | `input_synapses_by_layer.csv` | 3 | Input synapse counts for 160 excitatory neurons across four layers |
    | `morphometry.py` | 2 | `python3 morphometry.py --swc neurons/basket.swc --sholl 10` prints Sholl counts |

    For the warm-up the run-of-show describes a 20 x 30 matrix: take any 20 rows and
    30 columns of `celltype_synapses.csv`. For the "reconstructed neuron" in the
    warm-up, use `neurons/excitatory.swc`; a Sholl plot needs a skeleton, not a mesh.

    ```python
    import pandas as pd
    syn = pd.read_csv("celltype_synapses.csv", index_col="pre_type")
    conn = pd.read_csv("celltype_connections.csv", index_col="pre_type")
    sparse = conn < 10          # cells to hatch in Figure 1
    print(syn.shape, int(sparse.values.sum()), "sparse cells")
    ```

    **Units and honesty.** Counts are synapses; the uncertainty band in Figure 2 is
    your choice of method, and the caption must say what it is. A band built from
    `est_missing_cable_fraction` shows reconstruction incompleteness, not biological
    variability.
  MD
end

# ------------------------------------------------------------------ Modules 10 and 11 (graphs)

COLUMN_LAYERS = { 'L1' => [0, 100], 'L2/3' => [100, 350], 'L4' => [350, 500], 'L5' => [500, 750], 'L6' => [750, 950] }.freeze

def place(rng, layer)
  lo, hi = COLUMN_LAYERS.fetch(layer)
  [(rng.rand * 400).round(1), (lo + rng.rand * (hi - lo)).round(1), (rng.rand * 400).round(1)]
end

def geometric(rng, p)
  n = 1
  n += 1 while rng.rand > p
  n
end

def module10
  rng = Random.new(1010)
  dir = kit_dir(10)
  pop = { 'L23_pyr' => ['L2/3', 110], 'L4_exc' => ['L4', 90], 'L5_pyr' => ['L5', 90], 'L6_pyr' => ['L6', 80],
          'basket' => [nil, 46], 'martinotti' => [nil, 30], 'vip' => [nil, 24], 'neurogliaform' => ['L1', 18],
          'chandelier' => ['L2/3', 12] }
  nodes = []
  pop.each do |type, (layer, n)|
    n.times do
      l = layer || %w[L2/3 L4 L5 L6].sample(random: rng)
      nodes << { type: type, layer: l, pos: place(rng, l), somata: 1 }
    end
  end
  nodes.shuffle!(random: rng)
  nodes.each_with_index { |n, i| n[:id] = 20_001 + i }
  exc = %w[L23_pyr L4_exc L5_pyr L6_pyr]
  rate = lambda do |a, b|
    ea = exc.include?(a[:type])
    eb = exc.include?(b[:type])
    r = if ea && eb then a[:layer] == b[:layer] ? 0.10 : (a[:type] == 'L4_exc' && b[:type] == 'L23_pyr' ? 0.12 : 0.03)
        elsif ea then 0.22
        elsif eb then a[:type] == 'vip' ? 0.02 : 0.30
        else a[:type] == 'vip' ? 0.25 : 0.12
        end
    2.6 * r * Math.exp(-dist(a[:pos], b[:pos]) / 150.0)
  end
  edges = {}
  nodes.each do |a|
    nodes.each do |b|
      next if a.equal?(b)

      edges[[a[:id], b[:id]]] = geometric(rng, 0.55) if rng.rand < rate.call(a, b)
    end
  end
  # One planted merge: two basket cells fused into one object that carries both
  # partner lists and two somata. It becomes the dramatic "hub".
  # The two best-connected basket cells more than 300 µm apart are fused, so their
  # partner lists barely overlap and the object's degree is an outlier.
  degree = Hash.new(0)
  edges.each_key { |(p, q)| degree[p] += 1; degree[q] += 1 }
  baskets = nodes.select { |n| n[:type] == 'basket' }.sort_by { |n| [-degree[n[:id]], n[:id]] }
  keep = baskets.first
  gone = baskets.find { |n| dist(n[:pos], keep[:pos]) > 300 }
  if keep && gone
    edges.keys.select { |(p, q)| p == gone[:id] || q == gone[:id] }.each do |(p, q)|
      w = edges.delete([p, q])
      np = p == gone[:id] ? keep[:id] : p
      nq = q == gone[:id] ? keep[:id] : q
      next if np == nq

      edges[[np, nq]] = (edges[[np, nq]] || 0) + w
    end
    keep[:somata] = 2
    nodes.delete(gone)
  end
  # Top the population back up to 500 with one more L6 cell so the node count in the
  # module scenario holds.
  extra = { id: 20_001 + nodes.size + 1, type: 'L6_pyr', layer: 'L6', pos: place(rng, 'L6'), somata: 1 }
  nodes.each do |b|
    edges[[extra[:id], b[:id]]] = geometric(rng, 0.55) if rng.rand < rate.call(extra, b)
    edges[[b[:id], extra[:id]]] = geometric(rng, 0.55) if rng.rand < rate.call(b, extra)
  end
  nodes << extra
  nodes.sort_by! { |n| n[:id] }
  write_csv(File.join(dir, 'nodes.csv'), %w[node_id cell_type layer soma_x_um soma_y_um soma_z_um soma_count],
            nodes.map { |n| [n[:id], n[:type], n[:layer], n[:pos][0], n[:pos][1], n[:pos][2], n[:somata]] })
  write_csv(File.join(dir, 'edges.csv'), %w[pre_id post_id synapses],
            edges.sort.map { |(p, q), w| [p, q, w] })
  one = edges.values.count(1)
  write(File.join(dir, 'README.md'), <<~MD)
    # Module 10 kit: a 500-neuron column graph

    #{SYNTHETIC_BANNER}

    The graph for the Module 10 graph analysis report: #{nodes.size} neurons in a
    400 x 400 x 950 µm synthetic cortical column, #{delim(edges.size)} directed edges at a
    threshold of one synapse (#{(100.0 * one / edges.size).round}% of them carry exactly
    one synapse). It is shaped like a column extracted from a real cortical volume but is not one;
    the [Dataset Access](/datasets/access/) page lists how to pull a real one.

    | File | What it is |
    |---|---|
    | `nodes.csv` | One row per neuron: cell type, layer, soma position (y is depth from the pia) and the number of somata in the object |
    | `edges.csv` | One row per directed connection with its synapse count; filter `synapses >= 3` for the second threshold |

    ```python
    import pandas as pd
    nodes = pd.read_csv("nodes.csv")
    edges = pd.read_csv("edges.csv")
    print(len(nodes), len(edges), len(edges) / (len(nodes) * (len(nodes) - 1)))
    # networkx: nx.from_pandas_edgelist(edges, "pre_id", "post_id", "synapses", create_using=nx.DiGraph)
    ```

    **How it was built, which you need for the null-model discussion.** Connection
    probability depends on the two cell types and falls off with soma distance
    (length constant 150 µm). A degree-preserving null therefore does not remove the
    spatial structure; a spatial null would. One object in `nodes.csv` has
    `soma_count` 2. Treat what you find there the way the module's worked example does.
  MD
end

def module11
  rng = Random.new(1111)
  dir = kit_dir(11)
  pop = { 'L23_pyr' => ['L2/3', 90], 'L4_exc' => ['L4', 60], 'basket' => [nil, 25], 'martinotti' => [nil, 15],
          'vip' => [nil, 10] }
  nodes = []
  pop.each do |type, (layer, n)|
    n.times do
      l = layer || %w[L2/3 L4].sample(random: rng)
      nodes << { type: type, layer: l, pos: place(rng, l) }
    end
  end
  nodes.shuffle!(random: rng)
  nodes.each_with_index { |n, i| n[:id] = 30_001 + i }
  exc = %w[L23_pyr L4_exc]
  rate = lambda do |a, b|
    ea = exc.include?(a[:type])
    eb = exc.include?(b[:type])
    r = if ea && eb then a[:layer] == b[:layer] ? 0.05 : (a[:type] == 'L4_exc' ? 0.06 : 0.015)
        elsif ea then 0.14
        elsif eb then { 'basket' => 0.24, 'martinotti' => 0.16, 'vip' => 0.01 }[a[:type]]
        else a[:type] == 'vip' ? 0.20 : 0.06
        end
    2.7 * r * Math.exp(-dist(a[:pos], b[:pos]) / 120.0)
  end
  compartments = lambda do |pre, post|
    if exc.include?(pre[:type])
      exc.include?(post[:type]) ? { 'spine' => 0.8, 'distal_dendrite' => 0.15, 'proximal_dendrite' => 0.05 } :
                                  { 'proximal_dendrite' => 0.5, 'distal_dendrite' => 0.35, 'soma' => 0.15 }
    else
      case pre[:type]
      when 'basket' then { 'soma' => 0.55, 'proximal_dendrite' => 0.3, 'distal_dendrite' => 0.1, 'uncertain' => 0.05 }
      when 'martinotti' then { 'distal_dendrite' => 0.8, 'spine' => 0.1, 'uncertain' => 0.1 }
      else { 'distal_dendrite' => 0.5, 'proximal_dendrite' => 0.4, 'uncertain' => 0.1 }
      end
    end
  end
  synapses = []
  sid = 1
  nodes.each do |a|
    nodes.each do |b|
      next if a.equal?(b)
      next unless rng.rand < rate.call(a, b)

      geometric(rng, 0.5).times do
        comp = weighted_pick(rng, compartments.call(a, b))
        gray = if comp == 'uncertain' then 'uncertain'
               elsif exc.include?(a[:type]) then rng.rand < 0.95 ? 'asymmetric' : 'uncertain'
               else rng.rand < 0.9 ? 'symmetric' : 'uncertain'
               end
        loc = vadd(b[:pos], [gaussian(rng, 0, 30), gaussian(rng, 0, 30), gaussian(rng, 0, 30)])
        synapses << [sid, a[:id], b[:id], comp, gray, loc[0].round(1), loc[1].round(1), loc[2].round(1)]
        sid += 1
      end
    end
  end
  write_csv(File.join(dir, 'nodes.csv'), %w[node_id cell_type layer soma_x_um soma_y_um soma_z_um],
            nodes.sort_by { |n| n[:id] }.map { |n| [n[:id], n[:type], n[:layer], *n[:pos]] })
  write_csv(File.join(dir, 'synapses.csv'),
            %w[synapse_id pre_id post_id compartment gray_type x_um y_um z_um], synapses)
  edge_count = synapses.map { |s| [s[1], s[2]] }.uniq.size

  # Warm-up subgraph: 15 neurons whose mutual synapses total exactly 50. Search
  # spatially compact candidate sets until one fits; seeded, so it is reproducible.
  by_id = nodes.to_h { |n| [n[:id], n] }
  small = nil
  srng = Random.new(1112)
  2000.times do
    center = nodes.sample(random: srng)
    pool = nodes.sort_by { |n| dist(n[:pos], center[:pos]) }.first(30)
    set = pool.sample(15, random: srng).map { |n| n[:id] }
    inside = synapses.select { |s| set.include?(s[1]) && set.include?(s[2]) }
    next unless inside.size == 50
    next unless set.map { |i| by_id[i][:type] }.uniq.size >= 3

    small = [set, inside]
    break
  end
  raise 'no 15-neuron, 50-synapse subgraph found; change the search seed' unless small

  set, inside = small
  write_csv(File.join(dir, 'small_nodes.csv'), %w[node_id cell_type layer],
            set.sort.map { |i| [i, by_id[i][:type], by_id[i][:layer]] })
  write_csv(File.join(dir, 'small_synapses.csv'), %w[synapse_id pre_id post_id compartment gray_type],
            inside.map { |s| s.first(5) })
  write(File.join(dir, 'README.md'), <<~MD)
    # Module 11 kit: a 200-neuron L2/3-L4 subgraph with synapse-level detail

    #{SYNTHETIC_BANNER}

    The Module 11 motif activity needs two things the graph abstraction throws away:
    where each synapse lands, and its Gray type. This kit keeps both.

    | File | Used in | What it is |
    |---|---|---|
    | `small_nodes.csv`, `small_synapses.csv` | Run-of-show 24:00-38:00 | 15 neurons and the 50 synapses among them, for counting 3-node motifs by hand |
    | `nodes.csv` | Studio | #{nodes.size} neurons: cell type, layer (L2/3 or L4), soma position |
    | `synapses.csv` | Studio | #{delim(synapses.size)} synapses (#{delim(edge_count)} directed connections): pre, post, postsynaptic compartment, Gray type, position |

    Collapse `synapses.csv` to edges by counting rows per (`pre_id`, `post_id`); keep
    the count so you can re-run at a threshold of two synapses. DotMotif or NetworkX
    both work on the resulting edge list.

    **How it was built.** Connection probability depends on the two cell types and
    falls off with soma distance (length constant 120 µm). Basket-type cells place
    most synapses on the soma or proximal dendrite; Martinotti-type cells place most on
    distal dendrites. So a count of E to I to E loops will be enriched against a
    degree-preserving null largely because of cell-type composition and proximity,
    and splitting the loops by compartment will separate two different circuits. The
    alternative explanations the studio asks for are built in; the kit contains no
    "wiring rule" beyond type, distance and compartment preferences.
  MD
end

# ------------------------------------------------------------------ Module 12

def module12
  dir = kit_dir(12)
  write(File.join(dir, 'README.md'), <<~MD)
    # Module 12 kit: a query to profile

    #{SYNTHETIC_BANNER}

    The query to profile in the Module 12 run-of-show (20:00-34:00) and the sampled
    measurement in studio task 2. `profile_join.py` builds synthetic tables with the
    shape of the studio scenario (a synapse table scaled from 5 x 10^8 rows, a
    120,000-row segment table, cell types for 8,400 neurons) at a fraction you choose,
    then times one question two ways:

    1. **Join at query time:** for every synapse, look up the pre- and postsynaptic
       segment's neuron and that neuron's cell type, then count cell-type pairs.
    2. **Pre-joined:** the same count from a table where the cell types were written
       onto each synapse row once, in advance.

    ```bash
    python3 profile_join.py --fraction 0.001    # 0.1 % sample: 500,000 synapse rows
    python3 profile_join.py --fraction 0.0005   # halve it and check the scaling is linear
    ```

    It prints wall times, the extrapolation to the full table, and the ratio, as
    JSON. Python 3, no packages, no network.

    **What the numbers mean.** This is in-memory Python on your laptop. It shows the
    method: measure a sample, check that time scales with rows, extrapolate, then
    compare against a design that moves work out of the query. It does not estimate
    what a query against cloud object storage costs, where reading bytes, not joining
    them, usually dominates. Say that in your write-up.
  MD
end

# ------------------------------------------------------------------ Module 13

def module13
  rng = Random.new(1313)
  dir = kit_dir(13)
  classes = { 'axon' => 0.38, 'spiny_dendrite' => 0.27, 'smooth_dendrite' => 0.19, 'glia_process' => 0.12,
              'merged_object' => 0.04 }
  # class means: path, caliber mean, caliber var, branches, tortuosity, pre syn, post syn, mito fraction
  means = {
    'axon' => [34, 0.35, 0.020, 2.5, 1.25, 3.0, 1.0, 0.07],
    'spiny_dendrite' => [30, 0.60, 0.050, 3.0, 1.18, 0.5, 5.0, 0.09],
    'smooth_dendrite' => [29, 0.55, 0.040, 3.0, 1.16, 0.5, 4.0, 0.11],
    'glia_process' => [25, 0.45, 0.080, 3.5, 1.35, 0.3, 0.5, 0.04],
    'merged_object' => [50, 0.55, 0.120, 5.0, 1.30, 2.0, 4.0, 0.08]
  }
  # Parents have a kind, and a kind only yields certain classes: a pyramidal
  # parent gives axon and spiny-dendrite fragments, an interneuron gives axon and
  # smooth-dendrite fragments, glia give glial processes. So fragments of one
  # parent share both a class mix and a per-parent feature signature, which is
  # what makes a random row split leak.
  kinds = { 'axon' => %w[pyr int], 'spiny_dendrite' => %w[pyr], 'smooth_dendrite' => %w[int],
            'glia_process' => %w[glia], 'merged_object' => %w[pyr int glia] }
  neurons = Array.new(600) do |i|
    kind = i < 330 ? 'pyr' : (i < 500 ? 'int' : 'glia')
    { id: 40_001 + i, kind: kind, block: [rng.rand(8), rng.rand(8)], batch: "B#{rng.rand(6) + 1}",
      offset: Array.new(8) { gaussian(rng, 0, 0.6) }, stain: gaussian(rng, 0, 4) }
  end
  by_kind = neurons.group_by { |n| n[:kind] }
  blocks = Hash.new { |h, k| h[k] = gaussian(rng, 0, 12) } # staining offset per 100 µm block
  rows = []
  4000.times do |i|
    cls = weighted_pick(rng, classes)
    n = by_kind.values_at(*kinds[cls]).flatten.sample(random: rng)
    m = means[cls]
    f = m.each_with_index.map { |mu, k| mu * Math.exp(n[:offset][k] + gaussian(rng, 0, 0.3)) }
    intensity = 120 + blocks[n[:block]] + n[:stain] + gaussian(rng, 0, 1.5)
    contains_error = cls == 'merged_object' || rng.rand < { 'axon' => 0.22, 'spiny_dendrite' => 0.15,
                                                             'smooth_dendrite' => 0.18, 'glia_process' => 0.35 }[cls]
    x = n[:block][0] * 100 + rng.rand * 100
    y = n[:block][1] * 100 + rng.rand * 100
    rows << [format('F%04d', i + 1), n[:id], "#{n[:block][0]}-#{n[:block][1]}", n[:batch], x.round(1), y.round(1),
             f[0].round(1), f[1].round(3), f[2].round(4), f[3].round, f[4].round(3), f[5].round, f[6].round,
             f[7].round(3), intensity.round(1), cls, contains_error ? 1 : 0]
  end
  header = %w[fragment_id parent_neuron_id block_100um proofread_batch x_um y_um path_length_um
              caliber_mean_um caliber_var branch_count tortuosity pre_synapses post_synapses
              mito_volume_fraction mean_intensity label contains_error]
  write_csv(File.join(dir, 'fragments.csv'), header, rows)
  # Held-out domain: different staining. Intensity shifts, mitochondria are
  # under-segmented, and smooth dendrites lose the caliber cue that separated them.
  held = []
  1000.times do |i|
    cls = weighted_pick(rng, classes)
    m = means[cls].dup
    m[7] *= 0.55
    if cls == 'smooth_dendrite'
      m[1] = 0.30 # caliber now reads like an axon's
      m[6] = 1.5  # and faint postsynaptic densities go undetected
    end
    f = m.map { |mu| mu * Math.exp(gaussian(rng, 0, 0.55)) }
    contains_error = cls == 'merged_object' || rng.rand < 0.2
    held << [format('H%04d', i + 1), 90_001 + rng.rand(150), 'domain2', 'D2', '', '',
             f[0].round(1), f[1].round(3), f[2].round(4), f[3].round, f[4].round(3), f[5].round, f[6].round,
             f[7].round(3), (95 + gaussian(rng, 0, 8)).round(1), cls, contains_error ? 1 : 0]
  end
  write_csv(File.join(dir, 'heldout_domain.csv'), header, held)
  write(File.join(dir, 'README.md'), <<~MD)
    # Module 13 kit: labeled neurite fragments

    #{SYNTHETIC_BANNER}

    The fragment set for Module 13: 4,000 labeled fragments from 600
    neurons in five classes, plus 1,000 fragments from a second, differently stained
    domain for the transfer test.

    | File | What it is |
    |---|---|
    | `fragments.csv` | Training domain. Prevalences near 38 / 27 / 19 / 12 / 4 % |
    | `heldout_domain.csv` | Second domain, same columns. Use it once, at the end. |

    | Column | Meaning |
    |---|---|
    | `parent_neuron_id` | Group for a grouped split |
    | `block_100um`, `x_um`, `y_um` | 100 µm spatial tile and position, for a spatial-block split |
    | `proofread_batch` | Annotation batch, for a batch split |
    | `path_length_um` ... `mito_volume_fraction` | The morphological features from the module's Concept 1 |
    | `mean_intensity` | Raw image intensity. Read the module on what this encodes before you use it |
    | `label` | axon, spiny_dendrite, smooth_dendrite, glia_process, merged_object |
    | `contains_error` | 1 if a reviewer would find an error in this segment; the target for precision at *k* = 500 |

    **What is built in.** Fragments of one neuron share a per-neuron offset on every
    feature, so a random row split leaks. Fragments in one 100 µm block share an
    intensity offset. In the held-out domain, mitochondria are under-segmented and
    smooth dendrites lose their caliber and postsynaptic-density cues, so the drop is
    not uniform across classes.
    Your numbers will differ from the module's worked example; the direction of each
    change is what to compare.
  MD
end

# ------------------------------------------------------------------ Module 14

def module14
  dir = kit_dir(14)
  rows = [
    %w[A clean 42.0 0.61 0.44 0.17 142 0.89 210 24],
    %w[B clean 42.0 0.52 0.19 0.33 118 0.93 95 47],
    %w[A artifact 6.5 1.12 0.86 0.26 61 0.78 71 6],
    %w[B artifact 6.5 1.21 0.55 0.66 38 0.84 44 19]
  ]
  write_csv(File.join(dir, 'model_comparison.csv'),
            %w[model region traced_path_mm vi_total vi_split vi_merge erl_um boundary_f1 splits merges], rows)
  rng = Random.new(1414)
  causes = {
    'weak stain' => ['membrane contrast fades across a pale band; object boundary drawn through cytoplasm',
                     'two axons touch where both membranes are faint; no fold or gap in the sections'],
    'section loss' => ['error sits at a missing section; the neurite is continuous either side of the gap',
                       'object ends at a lost section and resumes as a new ID two sections later'],
    'fold' => ['a dark crease crosses the neurite; the merge follows the crease',
               'fold overlaps two processes in one section; they are joined only there'],
    'thin neurite' => ['axon narrows below 0.1 um for several sections and the model loses it',
                       'thin spine neck is cut from its head; contrast is normal'],
    'genuine ambiguity' => ['two processes run in contact for 3 um; experts disagree on where one ends',
                            'membrane is visible but its continuity across a tangential cut cannot be settled']
  }
  cases = []
  key = []
  30.times do |i|
    cause = causes.keys.sample(random: rng)
    region = %w[fold section\ loss].include?(cause) ? 'artifact' : (rng.rand < 0.3 ? 'artifact' : 'clean')
    model = rng.rand < 0.5 ? 'A' : 'B'
    type = if cause == 'thin neurite' || cause == 'section loss' then 'split'
           elsif cause == 'fold' then 'merge'
           else rng.rand < 0.5 ? 'split' : 'merge'
           end
    z0 = 1_000 + rng.rand(1_500)
    id = format('FC%02d', i + 1)
    cases << [id, model, region, type, "#{z0}-#{z0 + 2 + rng.rand(4)}", causes[cause].sample(random: rng)]
    key << [id, cause]
  end
  write_csv(File.join(dir, 'failure_cases.csv'), %w[case_id model region error_type sections observation], cases)
  write_csv(File.join(dir, 'failure_cases_key.csv'), %w[case_id cause], key)
  write(File.join(dir, 'README.md'), <<~MD)
    # Module 14 kit: model comparison by region and a failure-case log

    #{SYNTHETIC_BANNER}

    The Module 14 studio compares two segmentation models on a clean ground-truth
    region and a smaller artifact-heavy one. No public release ships two competing
    models with matched ground truth, so this kit supplies the evaluation outputs
    instead of the volumes.

    | File | Who opens it | What it is |
    |---|---|---|
    | `model_comparison.csv` | Learners | VI (total, split, merge), ERL, boundary F1, split and merge counts, per model and region. The clean rows are the worked example's numbers. |
    | `failure_cases.csv` | Learners | 30 failure cases, each with the viewer observation a reviewer wrote down. Classify the cause of at least 15. |
    | `failure_cases_key.csv` | Instructor | The cause each observation was written to illustrate. |

    Causes to choose from: weak stain, section loss, fold, thin neurite, genuine
    ambiguity. Some observations are written so that two causes are defensible; the
    key records one, and a well-argued alternative should get credit.

    **What this kit cannot teach.** Looking at the failures yourself. Do that on the
    subvolume you brought to class (pre-class preparation), and use this kit for the
    arithmetic and the model card.
  MD
end

# ------------------------------------------------------------------ Module 18

def module18
  rng = Random.new(1818)
  dir = kit_dir(18)
  segments = []
  2000.times do |i|
    kind = weighted_pick(rng, 'neuron' => 0.2, 'neurite' => 0.45, 'debris' => 0.35)
    vol = case kind
          when 'neuron' then 10**(2.3 + rng.rand * 0.9)
          when 'neurite' then 10**(0.0 + rng.rand * 2.0)
          else 10**(-2.0 + rng.rand * 1.9)
          end
    segments << { id: 500_001 + i, kind: kind, vol: vol, soma: kind == 'neuron' ? 1 : 0,
                  edge: rng.rand < (kind == 'neuron' ? 0.18 : 0.3) ? 1 : 0 }
  end
  big = segments.select { |s| s[:kind] != 'debris' }
  syn = []
  sid = 1
  30_000.times do
    real = rng.rand < 0.82
    pre = (real ? big : segments).sample(random: rng)
    post = (real ? big : segments).sample(random: rng)
    score = real ? (140 + gaussian(rng, 0, 35)).clamp(0, 255) : (35 + gaussian(rng, 0, 18)).clamp(0, 255)
    syn << [sid, pre[:id], post[:id], score.round, ((real ? 400 : 120) * Math.exp(gaussian(rng, 0, 0.5))).round]
    sid += 1
  end
  # Planted defects: duplicated rows, autapses, and IDs that are not in the segment table.
  dups = syn.sample(450, random: rng).map(&:dup)
  syn.sample(90, random: rng).each { |r| r[2] = r[1] }
  syn.sample(300, random: rng).each { |r| r[1] = 900_001 + rng.rand(5_000) }
  rows = (syn + dups).shuffle(random: rng)
  write_csv(File.join(dir, 'noisy_synapses.csv'), %w[synapse_id pre_segment_id post_segment_id cleft_score size_vx], rows)
  write_csv(File.join(dir, 'segments.csv'), %w[segment_id volume_um3 has_soma touches_boundary],
            segments.map { |s| [s[:id], format('%.4f', s[:vol]), s[:soma], s[:edge]] })
  types = %w[L23_pyr L4_exc L5_pyr basket martinotti vip]
  ct = segments.select { |s| s[:soma] == 1 }.map do |s|
    [s[:id], rng.rand < 0.12 ? '' : weighted_pick(rng, types.zip([30, 22, 20, 12, 8, 8]).to_h)]
  end
  write_csv(File.join(dir, 'cell_types.csv'), %w[segment_id cell_type], ct)
  write(File.join(dir, 'README.md'), <<~MD)
    # Module 18 kit: a noisy export to clean

    #{SYNTHETIC_BANNER}

    A small stand-in for the export in the Module 18 scenario. The scenario's tables
    are millions of rows; these are #{delim(rows.size)} synapses, #{delim(segments.size)} segments and
    #{ct.size} cell-type annotations, which is enough to see every defect and small
    enough to open on a laptop. Report counts as fractions so they transfer.

    | File | What it is |
    |---|---|
    | `noisy_synapses.csv` | Synapses with a cleft score (0-255). The score distribution is bimodal. |
    | `segments.csv` | Segment volumes spanning about five orders of magnitude, with soma and boundary flags |
    | `cell_types.csv` | Cell-type labels for segments with a soma; some are blank |

    Defects to find, each planted on purpose: duplicated synapse rows, autapses
    (pre equals post), synapse endpoints that are not in the segment table, a debris
    tail of tiny segments, boundary-touching neurons, and missing cell-type labels.

    **QC dashboard template.** Fill one row per metric before and after cleaning:

    | Metric | Before | After | Gate | Pass/fail |
    |---|---|---|---|---|
    | Synapse rows | | | | |
    | Duplicate rows | | | 0 | |
    | Autapses | | | stated policy | |
    | Endpoints not in segment table | | | 0 | |
    | Segments below your debris threshold | | | stated policy | |
    | Neurons touching the boundary | | | stated policy | |
    | Mean synapses per neuron | | | | |
    | Fraction of each cell type remaining | | | | |

    The preprocessing decision table has the columns given in the studio activity:
    issue, policy, threshold, rationale, impact.
  MD
end

# ------------------------------------------------------------------ Module 19

def module19
  dir = kit_dir(19)
  write(File.join(dir, 'mock-preprint.md'), <<~MD)
    # Mock preprint for the Module 19 review board

    > **Fictional teaching document.** This preprint does not exist. Its title,
    > authors, numbers, figures and claims were written for a peer-review exercise.
    > No analysis of any dataset was performed to produce it, and nothing in it is a
    > finding. The volume and its release T19 are fictional too; no real dataset,
    > release or consortium is being described. It is written to contain four
    > specific problems for reviewers to find.

    ## A feed-forward inhibitory motif is enriched in mouse visual cortex and may drive seizure propagation

    **Authors:** A. Author, B. Author, C. Author, and the Data Release Consortium

    ### Abstract

    Feed-forward inhibition shapes the timing of cortical responses. Using an
    electron microscopy connectome of a fictional mouse visual cortex volume
    (release T19), we counted all three-node motifs among 2,114 neurons with
    somata in the volume. A feed-forward inhibitory loop, in which a pyramidal cell
    drives both an interneuron and a second pyramidal cell that the interneuron also
    inhibits, was enriched 3.5-fold relative to a degree-preserving random graph
    (p < 0.001, Bonferroni-corrected across 13 motif classes). Because this motif
    controls the gain of excitation, it likely plays a causal role in seizure
    propagation, and it is a candidate target for anti-epileptic therapy.

    ### Methods (excerpt)

    [M1] Synapses were taken from the public synapse table. Neurons were included if
    their soma lay within the volume. Edges were defined as one or more synapses from
    one neuron to another. [M2] Motifs were counted with DotMotif. The null model was
    1,000 degree-preserving rewirings of the full graph. [M3] We tested three motifs
    of prior interest: the feed-forward inhibitory loop, the reciprocal excitatory
    pair, and the disinhibitory chain.

    ### Results (excerpt)

    [R1] The feed-forward inhibitory loop occurred 1,812 times, against a null mean of
    518 (SD 41). **Figure 1.** Observed count against the null distribution for the
    feed-forward inhibitory loop. Bars show the null histogram; the line shows the
    observed count. [R2] Loops were distributed across all layers sampled.
    **Figure 2.** Loop count per interneuron, sorted. Twelve interneurons participate
    in more than half of all loops. No error bars are shown.

    ### Discussion (excerpt)

    [D1] Our results establish that feed-forward inhibition is a dominant organizing
    principle of visual cortex. [D2] Given that disruption of feed-forward inhibition
    is observed in epilepsy, this motif likely plays a causal role in seizure
    propagation.

    ### Author contributions

    The Data Release Consortium contributed to this work.
  MD
  write(File.join(dir, 'review-form.md'), <<~MD)
    # Module 19 review form and ethics-risk checklist

    Use with the [mock preprint](mock-preprint.md). Cite paragraph labels
    ([M1], [R2], [D1]) and figure numbers in every comment.

    ## Structured review form

    | Section | Your entry |
    |---|---|
    | Claims the paper makes (list each, with its paragraph label) | |
    | Methods audit: what is missing, why it matters, what to add | |
    | Evidence gaps: which figure or number does not support which claim | |
    | Uncertainty: which figure panel hides it | |
    | Interpretation audit: the sentence that overclaims, and its bounded version | |
    | Recommendation (accept with revisions, major revisions, reject) and the concerns it rests on | |

    ## Ethics-risk checklist

    - [ ] **Human tissue.** Does the paper use human-derived data? If so, is consent and de-identification described?
    - [ ] **Attribution.** Can a reader tell who did what? Is a group listed without individual contributions?
    - [ ] **Data sharing.** Are the exact data version, code and derived tables available?
    - [ ] **Selective reporting.** Are all tested hypotheses reported, including the null results?

    ## Two example reviewer comments

    These were written for this session. They are not taken from a real review.

    **Comment 1.** "The methods do not state the synapse confidence threshold or how
    neurons touching the volume boundary were handled ([M1]). Both change the edge
    count, and truncated neurons lose partners non-uniformly. Please report the
    threshold, re-run the motif count at a second threshold, and state how many
    neurons were excluded or retained at the boundary."

    **Comment 2.** "The analysis is not convincing and the conclusions are overstated.
    The authors should do more work before this is publishable."

    Which comment could the authors act on tomorrow, and what is missing from the
    other?
  MD
  write(File.join(dir, 'README.md'), <<~MD)
    # Module 19 kit: mock preprint and review form

    > **Fictional teaching material.** The preprint in this kit does not exist and
    > reports no real analysis. It was written so that four problems are findable.

    | File | What it is |
    |---|---|
    | [`mock-preprint.md`](mock-preprint.md) | Abstract, methods, results with two figure legends, discussion and contributions, with four seeded issues |
    | [`review-form.md`](review-form.md) | Structured review form, ethics-risk checklist, and two example reviewer comments written for the session |

    **Instructor key (do not hand out).** The four seeded issues are: a methods gap
    ([M1] gives no synapse confidence threshold and no boundary handling); an
    overclaim ([D1] and [D2], "establish", "dominant organizing principle", "causal
    role"); an attribution problem (a consortium listed without individual
    contributions); and selective reporting ([M3] tests three motifs, the results
    discuss one). A strong review also notices that Figure 2 has no uncertainty and
    that twelve interneurons carrying half of all loops is a merge-error check the
    authors did not report.
  MD
end

# ------------------------------------------------------------------ manifest

def manifest
  files = Dir.glob(File.join(KITS, '**', '*')).select { |f| File.file?(f) }.sort
  files.reject! { |f| File.basename(f) == 'manifest.json' }
  hand = %w[qc_metrics.py morphometry.py profile_join.py]
  entries = files.map do |f|
    rel = f.sub("#{ROOT}/", '')
    {
      'path' => rel,
      'sha256' => Digest::SHA256.file(f).hexdigest,
      'bytes' => File.size(f),
      'source' => hand.include?(File.basename(f)) ? 'hand-written' : GENERATOR
    }
  end
  write(File.join(KITS, 'manifest.json'), JSON.pretty_generate(
    'description' => 'Every file under assets/kits/, with its checksum. Regenerate with ' \
                     "ruby #{GENERATOR}; scripts/validate_kit_materials.rb checks this list.",
    'files' => entries
  ))
  entries.size
end

module03
module06
module07
module09
module10
module11
module12
module13
module14
module16
module18
module19
count = manifest
puts "Generated kit materials; manifest lists #{count} files."
